name: Bug Report
description: Report incorrect calculations or unexpected behavior
title: "[BUG] "
labels: ["bug"]
body:
  - type: input
    id: calendar-system
    attributes:
      label: Calendar System
      description: Which calendar system has the issue?
      placeholder: "e.g. Gregorian, ISO, etc."
    validations:
      required: true

  - type: input
    id: expected
    attributes:
      label: Expected Result
      placeholder: "What result did you expect?"
    validations:
      required: true

  - type: input
    id: actual
    attributes:
      label: Actual Result
      placeholder: "What result did you get?"
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Code to Reproduce
      description: Minimal Rust code that shows the issue
      placeholder: |
        ```rust
        // Your code here
        ```
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other information that might be helpful
      placeholder: "Date ranges affected, error messages, etc."
