name: Feature Request
description: Request a new calendar system or feature
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      options:
        - New calendar system
        - API improvement
        - Performance enhancement
        - Documentation
        - Other
    validations:
      required: true

  - type: input
    id: calendar-name
    attributes:
      label: Calendar System (if applicable)
      placeholder: "e.g., Hebrew, Persian, Chinese, Mayan, etc."

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Why do you need this feature?
      placeholder: "Describe your specific use case or problem this would solve"
    validations:
      required: true

  - type: checkboxes
    id: references
    attributes:
      label: Reference Material
      description: Do you have algorithmic references?
      options:
        - label: Chapter/page in Dershowitz & Reingold
        - label: Academic sources available
        - label: Other reliable references

  - type: textarea
    id: reference-details
    attributes:
      label: Reference Details
      description: Specific citations or sources
      placeholder: "Book chapters, paper citations, URLs, etc."

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other relevant information
